'''Парсит погоду в определенном городе и выводит ее'''

import requests, bs4

def kyiv():  
    s=requests.get('https://ua.sinoptik.ua/погода-київ/10-днів')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())

def kharkiv():  
    s=requests.get('https://ua.sinoptik.ua/погода-харків/2018-03-13')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())

def odessa():  
    s=requests.get('https://ua.sinoptik.ua/погода-одесса-105805518')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())

def lvov():  
    s=requests.get('https://ua.sinoptik.ua/погода-львів')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())

def berlin():  
    s=requests.get('https://ua.sinoptik.ua/погода-берлін')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())    

def london():  
    s=requests.get('https://ua.sinoptik.ua/погода-лондон')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())

def barselona():  
    s=requests.get('https://ua.sinoptik.ua/погода-барселона')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())

def madrid():  
    s=requests.get('https://ua.sinoptik.ua/погода-мадрид-103117735')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())

def newyork():  
    s=requests.get('https://ua.sinoptik.ua/погода-нью-йорк')
    b=bs4.BeautifulSoup(s.text, "html.parser")
    p3=b.select('.temperature .p3')
    pogoda1=p3[0].getText()
    p4=b.select('.temperature .p4')
    pogoda2=p4[0].getText()
    p5=b.select('.temperature .p5')
    pogoda3=p5[0].getText()
    p6=b.select('.temperature .p6')
    pogoda4=p6[0].getText()
    print('Утром ' + 'в 8:00 ' + pogoda1 + ' в 11:00 ' + pogoda2)
    print('Днём ' + 'в 14:00 ' + pogoda3 + ' в 17:00 ' + pogoda4)
    p=b.select('.rSide .description')
    pogoda=p[0].getText()
    print(pogoda.strip())
